<?php

namespace Karismatik\ChatBotBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository
{
    public function getResponseByInput($pattern)
    {
        $qb = $this->createQueryBuilder('conversation');
        $qb->where($qb->expr()->like('LOWER(conversation.input)', 'LOWER(:pattern)'))
           ->setParameter('pattern', '%' . $pattern . '%');

       return $qb->getQuery()->getResult();
        $result = $qb->getQuery()->getResult();

        if ( ! is_array($result)) {
        return $result;
    }

        return array_shift($result);
    }
}
